/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Payment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer paymentId;
    private Integer userId;
    private BigDecimal amount;
    private LocalDateTime paymentDate;
    private String status;

    public Payment() {}

    public Payment(Payment value) {
        this.paymentId = value.paymentId;
        this.userId = value.userId;
        this.amount = value.amount;
        this.paymentDate = value.paymentDate;
        this.status = value.status;
    }

    public Payment(
        Integer paymentId,
        Integer userId,
        BigDecimal amount,
        LocalDateTime paymentDate,
        String status
    ) {
        this.paymentId = paymentId;
        this.userId = userId;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.status = status;
    }

    /**
     * Getter for <code>db.payment.payment_id</code>.
     */
    public Integer getPaymentId() {
        return this.paymentId;
    }

    /**
     * Setter for <code>db.payment.payment_id</code>.
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * Getter for <code>db.payment.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>db.payment.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>db.payment.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>db.payment.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>db.payment.payment_date</code>.
     */
    public LocalDateTime getPaymentDate() {
        return this.paymentDate;
    }

    /**
     * Setter for <code>db.payment.payment_date</code>.
     */
    public void setPaymentDate(LocalDateTime paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * Getter for <code>db.payment.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>db.payment.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Payment other = (Payment) obj;
        if (this.paymentId == null) {
            if (other.paymentId != null)
                return false;
        }
        else if (!this.paymentId.equals(other.paymentId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.paymentDate == null) {
            if (other.paymentDate != null)
                return false;
        }
        else if (!this.paymentDate.equals(other.paymentDate))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.paymentId == null) ? 0 : this.paymentId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.paymentDate == null) ? 0 : this.paymentDate.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Payment (");

        sb.append(paymentId);
        sb.append(", ").append(userId);
        sb.append(", ").append(amount);
        sb.append(", ").append(paymentDate);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
