/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Databasechangelog;
import jooq.tables.Databasechangeloglock;
import jooq.tables.Payment;
import jooq.tables.User;


/**
 * Convenience access to all tables in db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>db.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>db.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>db.payment</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>db.user</code>.
     */
    public static final User USER = User.USER;
}
